title: <p align="center" style="color:cyan"> KAVITA GUPTA 
logo: /assets/img/logo.png
description: I am working as Associate Consultant for Data Analytics project 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
