title: KAVITA GUPTA 
logo: /assets/img/photo.jpg
description: 
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/kavita-gupta-5a437568/">LinkedIn</a> |
  <a href="https://github.com/KavitaGupta2023">GitHub</a>
  <br>
  I am working as Associate Consultant for Data Analytics project having total experience of 12 years in IT industry
  </p>
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
